### ISSUE TITLE
Duplicite record for the same entry

### ISSUE THREAD

**Issue by Jemmotar** [Filipsi/ClipboardMachinery#2]
When I select some text to save, and I press multiple times the Ctr+C keys, it will create a record for each of the press of keys. Is possible please to check only for the last entry if the previous entry is not the same, from the same source?  It is happening only for text. If I try to copy some field at MS paint, it will do just one record no matter how many times I press the Ctr+C.
Example:
![image](https://user-images.githubusercontent.com/10741435/57509562-d27d4800-7304-11e9-956e-c66d53286b04.png)

**Comment by Filipsi** [comment]
There already is logic in place to handle this. It compares last string stored in the database with new clipboard content.
https://github.com/Filipsi/ClipboardMachinery/blob/0a329b02a76401b6e18e98c9472206a80095f1f6/ClipboardMachinery/ClipboardMachinery/Windows/Shell/ShellViewModel.cs#L128-L132


I have quickly tested this with notepad.exe and Notepad++ on version 1.0.69 and was unable to replicate the issue.

There were some problems when trying to copy from SearchUI (StartMenu in explorer.exe) that caused duplicates, but only two and right after each other.

**Comment by Jemmotar** [comment]
After reboot of my computer, it is again working fine everywhere except Microsoft Sticky Notes.
Bug is no longer critical.
[storage.sqlite.zip](https://github.com/Filipsi/ClipboardMachinery/files/3167357/storage.sqlite.zip)

**Comment by Filipsi** [comment]
After thinking about it for a while, there might be a concurrency issue that might only happen with slow disk write speed. Attempted fixing this with 6846d755be08a271821f47b81d1c66f7e686165e.

Let me know if it helps.
